// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvxUTO35-dOs8af7-R9XUlNQBsWQrscrw',
    appId: '1:455995635523:web:17a48719d89ba87320e1f6',
    messagingSenderId: '455995635523',
    projectId: 'digitalidentity-78618',
    authDomain: 'digitalidentity-78618.firebaseapp.com',
    storageBucket: 'digitalidentity-78618.appspot.com',
    measurementId: 'G-291JDWCVM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9TZzmRfs7Ku5cZZuG1F4lX-uJ515jsOw',
    appId: '1:455995635523:android:5f9fcacf73fc413820e1f6',
    messagingSenderId: '455995635523',
    projectId: 'digitalidentity-78618',
    storageBucket: 'digitalidentity-78618.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWUbyWwXRaAfyWDa7tmo56x_tO8cjaqYo',
    appId: '1:455995635523:ios:2927837290281f5420e1f6',
    messagingSenderId: '455995635523',
    projectId: 'digitalidentity-78618',
    storageBucket: 'digitalidentity-78618.appspot.com',
    iosClientId: '455995635523-2a2s5ab4b4i5m4n06ps6jtkdridmq8tv.apps.googleusercontent.com',
    iosBundleId: 'com.digital.identity.digitalIdentityUi',
  );
}
